### ISSUE TITLE
Clarification in test_sdfq comments

### ISSUE THREAD

**Issue by Dioprz** [Crypto-TII/CryptographicEstimators#158]
Hi,

Working on the SDFqEstimator tests, I stumbled upon this function:

https://github.com/Crypto-TII/CryptographicEstimators/blob/b5832c1eac7fb30edcea4250d4a9ae3df77b099b/tests/test_sdfq.sage#L20-L37

It's clear that we used `p=2` instead of `p=1` as the comment suggest. Any reason for this change that should be documented? Or can I safely remove this comment ?

**Comment by FloydZ** [comment]
As `p=2` is hardcoded in the function call, its fine for me to remove it.
