### ISSUE TITLE
Match docker and non docker commands functionality

### ISSUE THREAD

**Issue by Dioprz** [Crypto-TII/CryptographicEstimators#175]
Currently some non-docker commands defined in our `Makefile` implements a different logic from those defined for usage with docker. As a post-python migration step, and given that docker will be necessary mainly for CI/CD process only, we should integrate all the functionality in an appropriate way to the non-docker commands.

Example: `testfast` and `docker-testfast`, or `testall` and `docker-test`.

**Comment by Memphisd** [comment]
It would be great if until this is fully resolved, we could have a working `make install` installing all necessary packages including pytest and the necessary addons locally, if not too much effort.

**Comment by Dioprz** [comment]
@Memphisd Given that all the testing commands we're using during the migration are docker-based, I can't see a purpose for a local installation in the current state of the library. Could you clarify its intended purpose please? Is this suggestion for use after we've completed the migration?

In any case, I hope to address this very soon and will have in mind your suggestion.

**Comment by Memphisd** [comment]
There have been multiple cases, where we had some weird testing behavior running the docker version, which could not be reproduced across platforms. In those cases a different possibility to run the tests on the same machine would have allowed us to find the cause more quickly.

**Comment by Dioprz** [comment]
Solved in https://github.com/Crypto-TII/CryptographicEstimators/pull/201.
