### ISSUE TITLE
Docstrings HTML documentation concerns

### ISSUE THREAD

**Issue by Dioprz** [Crypto-TII/CryptographicEstimators#198]
This issue is to keep track of any concern regarding the HTML documentation generation, so we can adress them after the migration to pure Python is completed.

1. https://github.com/Crypto-TII/CryptographicEstimators/pull/179#discussion_r1787174737

**Comment by FloydZ** [comment]
this is also done, right?

**Comment by Dioprz** [comment]
Not completely. There are still one or two things linked that I need to fix.

**Comment by Dioprz** [comment]
All the concerns in the following PRs were solved (all related with docstrings indentation).

#179 (None)
#190
#193
#194


About https://github.com/Crypto-TII/CryptographicEstimators/pull/191#issuecomment-2396408964

> https://github.com/Crypto-TII/CryptographicEstimators/issues/198 It would be nice to change:
> From:
> 
> **kwargs --
> Additional keyword arguments.
> To
> 
> **kwargs -- Additional keyword arguments.

I have tried to fix this in many ways by changing what lines (with what indentation, order, etc) I return from our Sphinx extension (`kwargs_formatter.py`), but this changes aren't effectively impacting whatever is producing this kind of rendering.

At this point the most feasible candidates to fix this could be:
1. The Sphinx processing AFTER my parsing on the extension.
2. The HTML build tool.
3. Weird reST formatting rules (under the hood, all Sphinx does is translate from our Google docstyle into reST. That's why this is a candidate).

I don't think is worth to spend more time on this, but let me know what you all think. @FloydZ @Memphisd @Javierverbel. Feel free to close the issue if you agree.
